# docker-compose.yml
# This file uses the modern Docker Compose specification.
# The top-level 'version' key is no longer required.

services:
  mestre-tatu:
    # Build the Docker image from the Dockerfile in the current directory.
    # The image will be tagged based on the directory name.
    build: .

    # A friendly, predictable name for your container.
    container_name: mestre-tatu-bot

    # Ensures the bot restarts automatically if it crashes or the server reboots.
    # 'unless-stopped' means it won't start on boot if you manually stopped it.
    restart: unless-stopped

    # Load environment variables (your secrets) from the .env file.
    # Make sure your .env file is in the same directory as this file.
    env_file:
      - .env

    # This is the key for data persistence. It maps a local directory
    # on your server to the /data directory inside the container.
    # All databases and JSON files will be stored here, safe from container restarts.
    volumes:
      - ./data:/data