# fly.toml app configuration file for mestretatu
# See https://fly.io/docs/reference/configuration/ for more information

app = 'mestretatu'
primary_region = 'gru'

# --- CORREÇÃO: Configurações de uptime no nível superior ---
# Garante que a máquina nunca pare automaticamente e que sempre haja uma rodando.
auto_stop_machines = false
min_machines_running = 1

[build]

[env]
  DATA_DIR = "/data"

[processes]
  app = "./start.sh" # <-- Change this line

[mounts]
  source = "tatu_data"
  destination = "/data"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

# Define o serviço web para os health checks, mantendo o bot online.
[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # O health check HTTP que valida se o seu servidor web está respondendo.
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/"
    # Aumentado para dar mais tempo ao bot para iniciar antes da primeira verificação.
    grace_period = "30s"