# fly.toml app configuration file generated for mestretatu on 2025-07-04T04:09:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mestretatu'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  # --- CORREÇÃO: Configuração para um serviço 24/7 ---
  auto_stop_machines = false  # Impede que a máquina pare
  auto_start_machines = true
  min_machines_running = 1    # Garante que sempre haverá uma máquina rodando

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  # memory_mb is deprecated in favor of memory, so it can be removed.

[mounts]
  source = "tatu_data"
  destination = "/data"

[env]
  DATA_DIR = "/data"